// Code generated by "go run answers_generate.go"; DO NOT EDIT.

package zdns

func (ans *Answer) BaseAns() *Answer           { return ans }
func (ans *AFSDBAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *CAAAnswer) BaseAns() *Answer        { return &ans.Answer }
func (ans *CERTAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *CSYNCAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *DNSKEYAnswer) BaseAns() *Answer     { return &ans.Answer }
func (ans *DSAnswer) BaseAns() *Answer         { return &ans.Answer }
func (ans *GPOSAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *HINFOAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *HIPAnswer) BaseAns() *Answer        { return &ans.Answer }
func (ans *LOCAnswer) BaseAns() *Answer        { return &ans.Answer }
func (ans *MINFOAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *NAPTRAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *NSEC3Answer) BaseAns() *Answer      { return &ans.Answer }
func (ans *NSEC3ParamAnswer) BaseAns() *Answer { return &ans.Answer }
func (ans *NSECAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *PXAnswer) BaseAns() *Answer         { return &ans.Answer }
func (ans *PrefAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *RPAnswer) BaseAns() *Answer         { return &ans.Answer }
func (ans *RRSIGAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *SMIMEAAnswer) BaseAns() *Answer     { return &ans.Answer }
func (ans *SOAAnswer) BaseAns() *Answer        { return &ans.Answer }
func (ans *SRVAnswer) BaseAns() *Answer        { return &ans.Answer }
func (ans *SSHFPAnswer) BaseAns() *Answer      { return &ans.Answer }
func (ans *SVCBAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *TALINKAnswer) BaseAns() *Answer     { return &ans.Answer }
func (ans *TKEYAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *TLSAAnswer) BaseAns() *Answer       { return &ans.Answer }
func (ans *URIAnswer) BaseAns() *Answer        { return &ans.Answer }
